# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _algorithms
else:
    import _algorithms

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _algorithms.delete_SwigPyIterator

    def value(self):
        return _algorithms.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _algorithms.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _algorithms.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _algorithms.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _algorithms.SwigPyIterator_equal(self, x)

    def copy(self):
        return _algorithms.SwigPyIterator_copy(self)

    def next(self):
        return _algorithms.SwigPyIterator_next(self)

    def __next__(self):
        return _algorithms.SwigPyIterator___next__(self)

    def previous(self):
        return _algorithms.SwigPyIterator_previous(self)

    def advance(self, n):
        return _algorithms.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _algorithms.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _algorithms.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _algorithms.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _algorithms.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _algorithms.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _algorithms.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _algorithms:
_algorithms.SwigPyIterator_swigregister(SwigPyIterator)
class IntVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _algorithms.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _algorithms.IntVector___nonzero__(self)

    def __bool__(self):
        return _algorithms.IntVector___bool__(self)

    def __len__(self):
        return _algorithms.IntVector___len__(self)

    def __getslice__(self, i, j):
        return _algorithms.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _algorithms.IntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _algorithms.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _algorithms.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _algorithms.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _algorithms.IntVector___setitem__(self, *args)

    def pop(self):
        return _algorithms.IntVector_pop(self)

    def append(self, x):
        return _algorithms.IntVector_append(self, x)

    def empty(self):
        return _algorithms.IntVector_empty(self)

    def size(self):
        return _algorithms.IntVector_size(self)

    def swap(self, v):
        return _algorithms.IntVector_swap(self, v)

    def begin(self):
        return _algorithms.IntVector_begin(self)

    def end(self):
        return _algorithms.IntVector_end(self)

    def rbegin(self):
        return _algorithms.IntVector_rbegin(self)

    def rend(self):
        return _algorithms.IntVector_rend(self)

    def clear(self):
        return _algorithms.IntVector_clear(self)

    def get_allocator(self):
        return _algorithms.IntVector_get_allocator(self)

    def pop_back(self):
        return _algorithms.IntVector_pop_back(self)

    def erase(self, *args):
        return _algorithms.IntVector_erase(self, *args)

    def __init__(self, *args):
        _algorithms.IntVector_swiginit(self, _algorithms.new_IntVector(*args))

    def push_back(self, x):
        return _algorithms.IntVector_push_back(self, x)

    def front(self):
        return _algorithms.IntVector_front(self)

    def back(self):
        return _algorithms.IntVector_back(self)

    def assign(self, n, x):
        return _algorithms.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _algorithms.IntVector_resize(self, *args)

    def insert(self, *args):
        return _algorithms.IntVector_insert(self, *args)

    def reserve(self, n):
        return _algorithms.IntVector_reserve(self, n)

    def capacity(self):
        return _algorithms.IntVector_capacity(self)
    __swig_destroy__ = _algorithms.delete_IntVector

# Register IntVector in _algorithms:
_algorithms.IntVector_swigregister(IntVector)
class DoubleVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _algorithms.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _algorithms.DoubleVector___nonzero__(self)

    def __bool__(self):
        return _algorithms.DoubleVector___bool__(self)

    def __len__(self):
        return _algorithms.DoubleVector___len__(self)

    def __getslice__(self, i, j):
        return _algorithms.DoubleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _algorithms.DoubleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _algorithms.DoubleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _algorithms.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _algorithms.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _algorithms.DoubleVector___setitem__(self, *args)

    def pop(self):
        return _algorithms.DoubleVector_pop(self)

    def append(self, x):
        return _algorithms.DoubleVector_append(self, x)

    def empty(self):
        return _algorithms.DoubleVector_empty(self)

    def size(self):
        return _algorithms.DoubleVector_size(self)

    def swap(self, v):
        return _algorithms.DoubleVector_swap(self, v)

    def begin(self):
        return _algorithms.DoubleVector_begin(self)

    def end(self):
        return _algorithms.DoubleVector_end(self)

    def rbegin(self):
        return _algorithms.DoubleVector_rbegin(self)

    def rend(self):
        return _algorithms.DoubleVector_rend(self)

    def clear(self):
        return _algorithms.DoubleVector_clear(self)

    def get_allocator(self):
        return _algorithms.DoubleVector_get_allocator(self)

    def pop_back(self):
        return _algorithms.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _algorithms.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        _algorithms.DoubleVector_swiginit(self, _algorithms.new_DoubleVector(*args))

    def push_back(self, x):
        return _algorithms.DoubleVector_push_back(self, x)

    def front(self):
        return _algorithms.DoubleVector_front(self)

    def back(self):
        return _algorithms.DoubleVector_back(self)

    def assign(self, n, x):
        return _algorithms.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _algorithms.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _algorithms.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _algorithms.DoubleVector_reserve(self, n)

    def capacity(self):
        return _algorithms.DoubleVector_capacity(self)
    __swig_destroy__ = _algorithms.delete_DoubleVector

# Register DoubleVector in _algorithms:
_algorithms.DoubleVector_swigregister(DoubleVector)
class StrVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _algorithms.StrVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _algorithms.StrVector___nonzero__(self)

    def __bool__(self):
        return _algorithms.StrVector___bool__(self)

    def __len__(self):
        return _algorithms.StrVector___len__(self)

    def __getslice__(self, i, j):
        return _algorithms.StrVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _algorithms.StrVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _algorithms.StrVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _algorithms.StrVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _algorithms.StrVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _algorithms.StrVector___setitem__(self, *args)

    def pop(self):
        return _algorithms.StrVector_pop(self)

    def append(self, x):
        return _algorithms.StrVector_append(self, x)

    def empty(self):
        return _algorithms.StrVector_empty(self)

    def size(self):
        return _algorithms.StrVector_size(self)

    def swap(self, v):
        return _algorithms.StrVector_swap(self, v)

    def begin(self):
        return _algorithms.StrVector_begin(self)

    def end(self):
        return _algorithms.StrVector_end(self)

    def rbegin(self):
        return _algorithms.StrVector_rbegin(self)

    def rend(self):
        return _algorithms.StrVector_rend(self)

    def clear(self):
        return _algorithms.StrVector_clear(self)

    def get_allocator(self):
        return _algorithms.StrVector_get_allocator(self)

    def pop_back(self):
        return _algorithms.StrVector_pop_back(self)

    def erase(self, *args):
        return _algorithms.StrVector_erase(self, *args)

    def __init__(self, *args):
        _algorithms.StrVector_swiginit(self, _algorithms.new_StrVector(*args))

    def push_back(self, x):
        return _algorithms.StrVector_push_back(self, x)

    def front(self):
        return _algorithms.StrVector_front(self)

    def back(self):
        return _algorithms.StrVector_back(self)

    def assign(self, n, x):
        return _algorithms.StrVector_assign(self, n, x)

    def resize(self, *args):
        return _algorithms.StrVector_resize(self, *args)

    def insert(self, *args):
        return _algorithms.StrVector_insert(self, *args)

    def reserve(self, n):
        return _algorithms.StrVector_reserve(self, n)

    def capacity(self):
        return _algorithms.StrVector_capacity(self)
    __swig_destroy__ = _algorithms.delete_StrVector

# Register StrVector in _algorithms:
_algorithms.StrVector_swigregister(StrVector)
class IntDeque(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _algorithms.IntDeque_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _algorithms.IntDeque___nonzero__(self)

    def __bool__(self):
        return _algorithms.IntDeque___bool__(self)

    def __len__(self):
        return _algorithms.IntDeque___len__(self)

    def __getslice__(self, i, j):
        return _algorithms.IntDeque___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _algorithms.IntDeque___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _algorithms.IntDeque___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _algorithms.IntDeque___delitem__(self, *args)

    def __getitem__(self, *args):
        return _algorithms.IntDeque___getitem__(self, *args)

    def __setitem__(self, *args):
        return _algorithms.IntDeque___setitem__(self, *args)

    def pop(self):
        return _algorithms.IntDeque_pop(self)

    def append(self, x):
        return _algorithms.IntDeque_append(self, x)

    def empty(self):
        return _algorithms.IntDeque_empty(self)

    def size(self):
        return _algorithms.IntDeque_size(self)

    def swap(self, v):
        return _algorithms.IntDeque_swap(self, v)

    def begin(self):
        return _algorithms.IntDeque_begin(self)

    def end(self):
        return _algorithms.IntDeque_end(self)

    def rbegin(self):
        return _algorithms.IntDeque_rbegin(self)

    def rend(self):
        return _algorithms.IntDeque_rend(self)

    def clear(self):
        return _algorithms.IntDeque_clear(self)

    def get_allocator(self):
        return _algorithms.IntDeque_get_allocator(self)

    def pop_back(self):
        return _algorithms.IntDeque_pop_back(self)

    def erase(self, *args):
        return _algorithms.IntDeque_erase(self, *args)

    def __init__(self, *args):
        _algorithms.IntDeque_swiginit(self, _algorithms.new_IntDeque(*args))

    def push_back(self, x):
        return _algorithms.IntDeque_push_back(self, x)

    def front(self):
        return _algorithms.IntDeque_front(self)

    def back(self):
        return _algorithms.IntDeque_back(self)

    def assign(self, n, x):
        return _algorithms.IntDeque_assign(self, n, x)

    def resize(self, *args):
        return _algorithms.IntDeque_resize(self, *args)

    def insert(self, *args):
        return _algorithms.IntDeque_insert(self, *args)

    def pop_front(self):
        return _algorithms.IntDeque_pop_front(self)

    def push_front(self, x):
        return _algorithms.IntDeque_push_front(self, x)
    __swig_destroy__ = _algorithms.delete_IntDeque

# Register IntDeque in _algorithms:
_algorithms.IntDeque_swigregister(IntDeque)
class DoubleDeque(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _algorithms.DoubleDeque_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _algorithms.DoubleDeque___nonzero__(self)

    def __bool__(self):
        return _algorithms.DoubleDeque___bool__(self)

    def __len__(self):
        return _algorithms.DoubleDeque___len__(self)

    def __getslice__(self, i, j):
        return _algorithms.DoubleDeque___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _algorithms.DoubleDeque___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _algorithms.DoubleDeque___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _algorithms.DoubleDeque___delitem__(self, *args)

    def __getitem__(self, *args):
        return _algorithms.DoubleDeque___getitem__(self, *args)

    def __setitem__(self, *args):
        return _algorithms.DoubleDeque___setitem__(self, *args)

    def pop(self):
        return _algorithms.DoubleDeque_pop(self)

    def append(self, x):
        return _algorithms.DoubleDeque_append(self, x)

    def empty(self):
        return _algorithms.DoubleDeque_empty(self)

    def size(self):
        return _algorithms.DoubleDeque_size(self)

    def swap(self, v):
        return _algorithms.DoubleDeque_swap(self, v)

    def begin(self):
        return _algorithms.DoubleDeque_begin(self)

    def end(self):
        return _algorithms.DoubleDeque_end(self)

    def rbegin(self):
        return _algorithms.DoubleDeque_rbegin(self)

    def rend(self):
        return _algorithms.DoubleDeque_rend(self)

    def clear(self):
        return _algorithms.DoubleDeque_clear(self)

    def get_allocator(self):
        return _algorithms.DoubleDeque_get_allocator(self)

    def pop_back(self):
        return _algorithms.DoubleDeque_pop_back(self)

    def erase(self, *args):
        return _algorithms.DoubleDeque_erase(self, *args)

    def __init__(self, *args):
        _algorithms.DoubleDeque_swiginit(self, _algorithms.new_DoubleDeque(*args))

    def push_back(self, x):
        return _algorithms.DoubleDeque_push_back(self, x)

    def front(self):
        return _algorithms.DoubleDeque_front(self)

    def back(self):
        return _algorithms.DoubleDeque_back(self)

    def assign(self, n, x):
        return _algorithms.DoubleDeque_assign(self, n, x)

    def resize(self, *args):
        return _algorithms.DoubleDeque_resize(self, *args)

    def insert(self, *args):
        return _algorithms.DoubleDeque_insert(self, *args)

    def pop_front(self):
        return _algorithms.DoubleDeque_pop_front(self)

    def push_front(self, x):
        return _algorithms.DoubleDeque_push_front(self, x)
    __swig_destroy__ = _algorithms.delete_DoubleDeque

# Register DoubleDeque in _algorithms:
_algorithms.DoubleDeque_swigregister(DoubleDeque)
class StrDeque(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _algorithms.StrDeque_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _algorithms.StrDeque___nonzero__(self)

    def __bool__(self):
        return _algorithms.StrDeque___bool__(self)

    def __len__(self):
        return _algorithms.StrDeque___len__(self)

    def __getslice__(self, i, j):
        return _algorithms.StrDeque___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _algorithms.StrDeque___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _algorithms.StrDeque___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _algorithms.StrDeque___delitem__(self, *args)

    def __getitem__(self, *args):
        return _algorithms.StrDeque___getitem__(self, *args)

    def __setitem__(self, *args):
        return _algorithms.StrDeque___setitem__(self, *args)

    def pop(self):
        return _algorithms.StrDeque_pop(self)

    def append(self, x):
        return _algorithms.StrDeque_append(self, x)

    def empty(self):
        return _algorithms.StrDeque_empty(self)

    def size(self):
        return _algorithms.StrDeque_size(self)

    def swap(self, v):
        return _algorithms.StrDeque_swap(self, v)

    def begin(self):
        return _algorithms.StrDeque_begin(self)

    def end(self):
        return _algorithms.StrDeque_end(self)

    def rbegin(self):
        return _algorithms.StrDeque_rbegin(self)

    def rend(self):
        return _algorithms.StrDeque_rend(self)

    def clear(self):
        return _algorithms.StrDeque_clear(self)

    def get_allocator(self):
        return _algorithms.StrDeque_get_allocator(self)

    def pop_back(self):
        return _algorithms.StrDeque_pop_back(self)

    def erase(self, *args):
        return _algorithms.StrDeque_erase(self, *args)

    def __init__(self, *args):
        _algorithms.StrDeque_swiginit(self, _algorithms.new_StrDeque(*args))

    def push_back(self, x):
        return _algorithms.StrDeque_push_back(self, x)

    def front(self):
        return _algorithms.StrDeque_front(self)

    def back(self):
        return _algorithms.StrDeque_back(self)

    def assign(self, n, x):
        return _algorithms.StrDeque_assign(self, n, x)

    def resize(self, *args):
        return _algorithms.StrDeque_resize(self, *args)

    def insert(self, *args):
        return _algorithms.StrDeque_insert(self, *args)

    def pop_front(self):
        return _algorithms.StrDeque_pop_front(self)

    def push_front(self, x):
        return _algorithms.StrDeque_push_front(self, x)
    __swig_destroy__ = _algorithms.delete_StrDeque

# Register StrDeque in _algorithms:
_algorithms.StrDeque_swigregister(StrDeque)

def sort_IntVector(c):
    return _algorithms.sort_IntVector(c)

def sort_DoubleVector(c):
    return _algorithms.sort_DoubleVector(c)

def sort_StrVector(c):
    return _algorithms.sort_StrVector(c)

def stable_sort_IntVector(c):
    return _algorithms.stable_sort_IntVector(c)

def stable_sort_DoubleVector(c):
    return _algorithms.stable_sort_DoubleVector(c)

def stable_sort_StrVector(c):
    return _algorithms.stable_sort_StrVector(c)

def reverse_IntVector(c):
    return _algorithms.reverse_IntVector(c)

def reverse_DoubleVector(c):
    return _algorithms.reverse_DoubleVector(c)

def reverse_StrVector(c):
    return _algorithms.reverse_StrVector(c)

def binary_search_IntVector(c, value):
    return _algorithms.binary_search_IntVector(c, value)

def binary_search_DoubleVector(c, value):
    return _algorithms.binary_search_DoubleVector(c, value)

def binary_search_StrVector(c, value):
    return _algorithms.binary_search_StrVector(c, value)

def lower_bound_IntVector(c, value):
    return _algorithms.lower_bound_IntVector(c, value)

def lower_bound_DoubleVector(c, value):
    return _algorithms.lower_bound_DoubleVector(c, value)

def lower_bound_StrVector(c, value):
    return _algorithms.lower_bound_StrVector(c, value)

def upper_bound_IntVector(c, value):
    return _algorithms.upper_bound_IntVector(c, value)

def upper_bound_DoubleVector(c, value):
    return _algorithms.upper_bound_DoubleVector(c, value)

def upper_bound_StrVector(c, value):
    return _algorithms.upper_bound_StrVector(c, value)

def sort_IntDeque(c):
    return _algorithms.sort_IntDeque(c)

def sort_DoubleDeque(c):
    return _algorithms.sort_DoubleDeque(c)

def sort_StrDeque(c):
    return _algorithms.sort_StrDeque(c)

def stable_sort_IntDeque(c):
    return _algorithms.stable_sort_IntDeque(c)

def stable_sort_DoubleDeque(c):
    return _algorithms.stable_sort_DoubleDeque(c)

def stable_sort_StrDeque(c):
    return _algorithms.stable_sort_StrDeque(c)

def reverse_IntDeque(c):
    return _algorithms.reverse_IntDeque(c)

def reverse_DoubleDeque(c):
    return _algorithms.reverse_DoubleDeque(c)

def reverse_StrDeque(c):
    return _algorithms.reverse_StrDeque(c)

def binary_search_IntDeque(c, value):
    return _algorithms.binary_search_IntDeque(c, value)

def binary_search_DoubleDeque(c, value):
    return _algorithms.binary_search_DoubleDeque(c, value)

def binary_search_StrDeque(c, value):
    return _algorithms.binary_search_StrDeque(c, value)

def lower_bound_IntDeque(c, value):
    return _algorithms.lower_bound_IntDeque(c, value)

def lower_bound_DoubleDeque(c, value):
    return _algorithms.lower_bound_DoubleDeque(c, value)

def lower_bound_StrDeque(c, value):
    return _algorithms.lower_bound_StrDeque(c, value)

def upper_bound_IntDeque(c, value):
    return _algorithms.upper_bound_IntDeque(c, value)

def upper_bound_DoubleDeque(c, value):
    return _algorithms.upper_bound_DoubleDeque(c, value)

def upper_bound_StrDeque(c, value):
    return _algorithms.upper_bound_StrDeque(c, value)

