# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _deque
else:
    import _deque

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _deque.delete_SwigPyIterator

    def value(self):
        return _deque.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _deque.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _deque.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _deque.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _deque.SwigPyIterator_equal(self, x)

    def copy(self):
        return _deque.SwigPyIterator_copy(self)

    def next(self):
        return _deque.SwigPyIterator_next(self)

    def __next__(self):
        return _deque.SwigPyIterator___next__(self)

    def previous(self):
        return _deque.SwigPyIterator_previous(self)

    def advance(self, n):
        return _deque.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _deque.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _deque.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _deque.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _deque.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _deque.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _deque.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _deque:
_deque.SwigPyIterator_swigregister(SwigPyIterator)
class IntDeque(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _deque.IntDeque_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _deque.IntDeque___nonzero__(self)

    def __bool__(self):
        return _deque.IntDeque___bool__(self)

    def __len__(self):
        return _deque.IntDeque___len__(self)

    def __getslice__(self, i, j):
        return _deque.IntDeque___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _deque.IntDeque___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _deque.IntDeque___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _deque.IntDeque___delitem__(self, *args)

    def __getitem__(self, *args):
        return _deque.IntDeque___getitem__(self, *args)

    def __setitem__(self, *args):
        return _deque.IntDeque___setitem__(self, *args)

    def pop(self):
        return _deque.IntDeque_pop(self)

    def append(self, x):
        return _deque.IntDeque_append(self, x)

    def empty(self):
        return _deque.IntDeque_empty(self)

    def size(self):
        return _deque.IntDeque_size(self)

    def swap(self, v):
        return _deque.IntDeque_swap(self, v)

    def begin(self):
        return _deque.IntDeque_begin(self)

    def end(self):
        return _deque.IntDeque_end(self)

    def rbegin(self):
        return _deque.IntDeque_rbegin(self)

    def rend(self):
        return _deque.IntDeque_rend(self)

    def clear(self):
        return _deque.IntDeque_clear(self)

    def get_allocator(self):
        return _deque.IntDeque_get_allocator(self)

    def pop_back(self):
        return _deque.IntDeque_pop_back(self)

    def erase(self, *args):
        return _deque.IntDeque_erase(self, *args)

    def __init__(self, *args):
        _deque.IntDeque_swiginit(self, _deque.new_IntDeque(*args))

    def push_back(self, x):
        return _deque.IntDeque_push_back(self, x)

    def front(self):
        return _deque.IntDeque_front(self)

    def back(self):
        return _deque.IntDeque_back(self)

    def assign(self, n, x):
        return _deque.IntDeque_assign(self, n, x)

    def resize(self, *args):
        return _deque.IntDeque_resize(self, *args)

    def insert(self, *args):
        return _deque.IntDeque_insert(self, *args)

    def pop_front(self):
        return _deque.IntDeque_pop_front(self)

    def push_front(self, x):
        return _deque.IntDeque_push_front(self, x)
    __swig_destroy__ = _deque.delete_IntDeque

# Register IntDeque in _deque:
_deque.IntDeque_swigregister(IntDeque)
class DoubleDeque(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _deque.DoubleDeque_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _deque.DoubleDeque___nonzero__(self)

    def __bool__(self):
        return _deque.DoubleDeque___bool__(self)

    def __len__(self):
        return _deque.DoubleDeque___len__(self)

    def __getslice__(self, i, j):
        return _deque.DoubleDeque___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _deque.DoubleDeque___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _deque.DoubleDeque___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _deque.DoubleDeque___delitem__(self, *args)

    def __getitem__(self, *args):
        return _deque.DoubleDeque___getitem__(self, *args)

    def __setitem__(self, *args):
        return _deque.DoubleDeque___setitem__(self, *args)

    def pop(self):
        return _deque.DoubleDeque_pop(self)

    def append(self, x):
        return _deque.DoubleDeque_append(self, x)

    def empty(self):
        return _deque.DoubleDeque_empty(self)

    def size(self):
        return _deque.DoubleDeque_size(self)

    def swap(self, v):
        return _deque.DoubleDeque_swap(self, v)

    def begin(self):
        return _deque.DoubleDeque_begin(self)

    def end(self):
        return _deque.DoubleDeque_end(self)

    def rbegin(self):
        return _deque.DoubleDeque_rbegin(self)

    def rend(self):
        return _deque.DoubleDeque_rend(self)

    def clear(self):
        return _deque.DoubleDeque_clear(self)

    def get_allocator(self):
        return _deque.DoubleDeque_get_allocator(self)

    def pop_back(self):
        return _deque.DoubleDeque_pop_back(self)

    def erase(self, *args):
        return _deque.DoubleDeque_erase(self, *args)

    def __init__(self, *args):
        _deque.DoubleDeque_swiginit(self, _deque.new_DoubleDeque(*args))

    def push_back(self, x):
        return _deque.DoubleDeque_push_back(self, x)

    def front(self):
        return _deque.DoubleDeque_front(self)

    def back(self):
        return _deque.DoubleDeque_back(self)

    def assign(self, n, x):
        return _deque.DoubleDeque_assign(self, n, x)

    def resize(self, *args):
        return _deque.DoubleDeque_resize(self, *args)

    def insert(self, *args):
        return _deque.DoubleDeque_insert(self, *args)

    def pop_front(self):
        return _deque.DoubleDeque_pop_front(self)

    def push_front(self, x):
        return _deque.DoubleDeque_push_front(self, x)
    __swig_destroy__ = _deque.delete_DoubleDeque

# Register DoubleDeque in _deque:
_deque.DoubleDeque_swigregister(DoubleDeque)
class StrDeque(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _deque.StrDeque_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _deque.StrDeque___nonzero__(self)

    def __bool__(self):
        return _deque.StrDeque___bool__(self)

    def __len__(self):
        return _deque.StrDeque___len__(self)

    def __getslice__(self, i, j):
        return _deque.StrDeque___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _deque.StrDeque___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _deque.StrDeque___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _deque.StrDeque___delitem__(self, *args)

    def __getitem__(self, *args):
        return _deque.StrDeque___getitem__(self, *args)

    def __setitem__(self, *args):
        return _deque.StrDeque___setitem__(self, *args)

    def pop(self):
        return _deque.StrDeque_pop(self)

    def append(self, x):
        return _deque.StrDeque_append(self, x)

    def empty(self):
        return _deque.StrDeque_empty(self)

    def size(self):
        return _deque.StrDeque_size(self)

    def swap(self, v):
        return _deque.StrDeque_swap(self, v)

    def begin(self):
        return _deque.StrDeque_begin(self)

    def end(self):
        return _deque.StrDeque_end(self)

    def rbegin(self):
        return _deque.StrDeque_rbegin(self)

    def rend(self):
        return _deque.StrDeque_rend(self)

    def clear(self):
        return _deque.StrDeque_clear(self)

    def get_allocator(self):
        return _deque.StrDeque_get_allocator(self)

    def pop_back(self):
        return _deque.StrDeque_pop_back(self)

    def erase(self, *args):
        return _deque.StrDeque_erase(self, *args)

    def __init__(self, *args):
        _deque.StrDeque_swiginit(self, _deque.new_StrDeque(*args))

    def push_back(self, x):
        return _deque.StrDeque_push_back(self, x)

    def front(self):
        return _deque.StrDeque_front(self)

    def back(self):
        return _deque.StrDeque_back(self)

    def assign(self, n, x):
        return _deque.StrDeque_assign(self, n, x)

    def resize(self, *args):
        return _deque.StrDeque_resize(self, *args)

    def insert(self, *args):
        return _deque.StrDeque_insert(self, *args)

    def pop_front(self):
        return _deque.StrDeque_pop_front(self)

    def push_front(self, x):
        return _deque.StrDeque_push_front(self, x)
    __swig_destroy__ = _deque.delete_StrDeque

# Register StrDeque in _deque:
_deque.StrDeque_swigregister(StrDeque)

