# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _map
else:
    import _map

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _map.delete_SwigPyIterator

    def value(self):
        return _map.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _map.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _map.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _map.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _map.SwigPyIterator_equal(self, x)

    def copy(self):
        return _map.SwigPyIterator_copy(self)

    def next(self):
        return _map.SwigPyIterator_next(self)

    def __next__(self):
        return _map.SwigPyIterator___next__(self)

    def previous(self):
        return _map.SwigPyIterator_previous(self)

    def advance(self, n):
        return _map.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _map.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _map.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _map.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _map.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _map.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _map.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _map:
_map.SwigPyIterator_swigregister(SwigPyIterator)
class IntIntMap(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _map.IntIntMap_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _map.IntIntMap___nonzero__(self)

    def __bool__(self):
        return _map.IntIntMap___bool__(self)

    def __len__(self):
        return _map.IntIntMap___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _map.IntIntMap___getitem__(self, key)

    def __delitem__(self, key):
        return _map.IntIntMap___delitem__(self, key)

    def has_key(self, key):
        return _map.IntIntMap_has_key(self, key)

    def keys(self):
        return _map.IntIntMap_keys(self)

    def values(self):
        return _map.IntIntMap_values(self)

    def items(self):
        return _map.IntIntMap_items(self)

    def __contains__(self, key):
        return _map.IntIntMap___contains__(self, key)

    def key_iterator(self):
        return _map.IntIntMap_key_iterator(self)

    def value_iterator(self):
        return _map.IntIntMap_value_iterator(self)

    def __setitem__(self, *args):
        return _map.IntIntMap___setitem__(self, *args)

    def asdict(self):
        return _map.IntIntMap_asdict(self)

    def __init__(self, *args):
        _map.IntIntMap_swiginit(self, _map.new_IntIntMap(*args))

    def empty(self):
        return _map.IntIntMap_empty(self)

    def size(self):
        return _map.IntIntMap_size(self)

    def swap(self, v):
        return _map.IntIntMap_swap(self, v)

    def begin(self):
        return _map.IntIntMap_begin(self)

    def end(self):
        return _map.IntIntMap_end(self)

    def rbegin(self):
        return _map.IntIntMap_rbegin(self)

    def rend(self):
        return _map.IntIntMap_rend(self)

    def clear(self):
        return _map.IntIntMap_clear(self)

    def get_allocator(self):
        return _map.IntIntMap_get_allocator(self)

    def count(self, x):
        return _map.IntIntMap_count(self, x)

    def erase(self, *args):
        return _map.IntIntMap_erase(self, *args)

    def find(self, x):
        return _map.IntIntMap_find(self, x)

    def lower_bound(self, x):
        return _map.IntIntMap_lower_bound(self, x)

    def upper_bound(self, x):
        return _map.IntIntMap_upper_bound(self, x)
    __swig_destroy__ = _map.delete_IntIntMap

# Register IntIntMap in _map:
_map.IntIntMap_swigregister(IntIntMap)
class IntDoubleMap(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _map.IntDoubleMap_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _map.IntDoubleMap___nonzero__(self)

    def __bool__(self):
        return _map.IntDoubleMap___bool__(self)

    def __len__(self):
        return _map.IntDoubleMap___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _map.IntDoubleMap___getitem__(self, key)

    def __delitem__(self, key):
        return _map.IntDoubleMap___delitem__(self, key)

    def has_key(self, key):
        return _map.IntDoubleMap_has_key(self, key)

    def keys(self):
        return _map.IntDoubleMap_keys(self)

    def values(self):
        return _map.IntDoubleMap_values(self)

    def items(self):
        return _map.IntDoubleMap_items(self)

    def __contains__(self, key):
        return _map.IntDoubleMap___contains__(self, key)

    def key_iterator(self):
        return _map.IntDoubleMap_key_iterator(self)

    def value_iterator(self):
        return _map.IntDoubleMap_value_iterator(self)

    def __setitem__(self, *args):
        return _map.IntDoubleMap___setitem__(self, *args)

    def asdict(self):
        return _map.IntDoubleMap_asdict(self)

    def __init__(self, *args):
        _map.IntDoubleMap_swiginit(self, _map.new_IntDoubleMap(*args))

    def empty(self):
        return _map.IntDoubleMap_empty(self)

    def size(self):
        return _map.IntDoubleMap_size(self)

    def swap(self, v):
        return _map.IntDoubleMap_swap(self, v)

    def begin(self):
        return _map.IntDoubleMap_begin(self)

    def end(self):
        return _map.IntDoubleMap_end(self)

    def rbegin(self):
        return _map.IntDoubleMap_rbegin(self)

    def rend(self):
        return _map.IntDoubleMap_rend(self)

    def clear(self):
        return _map.IntDoubleMap_clear(self)

    def get_allocator(self):
        return _map.IntDoubleMap_get_allocator(self)

    def count(self, x):
        return _map.IntDoubleMap_count(self, x)

    def erase(self, *args):
        return _map.IntDoubleMap_erase(self, *args)

    def find(self, x):
        return _map.IntDoubleMap_find(self, x)

    def lower_bound(self, x):
        return _map.IntDoubleMap_lower_bound(self, x)

    def upper_bound(self, x):
        return _map.IntDoubleMap_upper_bound(self, x)
    __swig_destroy__ = _map.delete_IntDoubleMap

# Register IntDoubleMap in _map:
_map.IntDoubleMap_swigregister(IntDoubleMap)
class StrIntMap(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _map.StrIntMap_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _map.StrIntMap___nonzero__(self)

    def __bool__(self):
        return _map.StrIntMap___bool__(self)

    def __len__(self):
        return _map.StrIntMap___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _map.StrIntMap___getitem__(self, key)

    def __delitem__(self, key):
        return _map.StrIntMap___delitem__(self, key)

    def has_key(self, key):
        return _map.StrIntMap_has_key(self, key)

    def keys(self):
        return _map.StrIntMap_keys(self)

    def values(self):
        return _map.StrIntMap_values(self)

    def items(self):
        return _map.StrIntMap_items(self)

    def __contains__(self, key):
        return _map.StrIntMap___contains__(self, key)

    def key_iterator(self):
        return _map.StrIntMap_key_iterator(self)

    def value_iterator(self):
        return _map.StrIntMap_value_iterator(self)

    def __setitem__(self, *args):
        return _map.StrIntMap___setitem__(self, *args)

    def asdict(self):
        return _map.StrIntMap_asdict(self)

    def __init__(self, *args):
        _map.StrIntMap_swiginit(self, _map.new_StrIntMap(*args))

    def empty(self):
        return _map.StrIntMap_empty(self)

    def size(self):
        return _map.StrIntMap_size(self)

    def swap(self, v):
        return _map.StrIntMap_swap(self, v)

    def begin(self):
        return _map.StrIntMap_begin(self)

    def end(self):
        return _map.StrIntMap_end(self)

    def rbegin(self):
        return _map.StrIntMap_rbegin(self)

    def rend(self):
        return _map.StrIntMap_rend(self)

    def clear(self):
        return _map.StrIntMap_clear(self)

    def get_allocator(self):
        return _map.StrIntMap_get_allocator(self)

    def count(self, x):
        return _map.StrIntMap_count(self, x)

    def erase(self, *args):
        return _map.StrIntMap_erase(self, *args)

    def find(self, x):
        return _map.StrIntMap_find(self, x)

    def lower_bound(self, x):
        return _map.StrIntMap_lower_bound(self, x)

    def upper_bound(self, x):
        return _map.StrIntMap_upper_bound(self, x)
    __swig_destroy__ = _map.delete_StrIntMap

# Register StrIntMap in _map:
_map.StrIntMap_swigregister(StrIntMap)
class StrStrMap(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _map.StrStrMap_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _map.StrStrMap___nonzero__(self)

    def __bool__(self):
        return _map.StrStrMap___bool__(self)

    def __len__(self):
        return _map.StrStrMap___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _map.StrStrMap___getitem__(self, key)

    def __delitem__(self, key):
        return _map.StrStrMap___delitem__(self, key)

    def has_key(self, key):
        return _map.StrStrMap_has_key(self, key)

    def keys(self):
        return _map.StrStrMap_keys(self)

    def values(self):
        return _map.StrStrMap_values(self)

    def items(self):
        return _map.StrStrMap_items(self)

    def __contains__(self, key):
        return _map.StrStrMap___contains__(self, key)

    def key_iterator(self):
        return _map.StrStrMap_key_iterator(self)

    def value_iterator(self):
        return _map.StrStrMap_value_iterator(self)

    def __setitem__(self, *args):
        return _map.StrStrMap___setitem__(self, *args)

    def asdict(self):
        return _map.StrStrMap_asdict(self)

    def __init__(self, *args):
        _map.StrStrMap_swiginit(self, _map.new_StrStrMap(*args))

    def empty(self):
        return _map.StrStrMap_empty(self)

    def size(self):
        return _map.StrStrMap_size(self)

    def swap(self, v):
        return _map.StrStrMap_swap(self, v)

    def begin(self):
        return _map.StrStrMap_begin(self)

    def end(self):
        return _map.StrStrMap_end(self)

    def rbegin(self):
        return _map.StrStrMap_rbegin(self)

    def rend(self):
        return _map.StrStrMap_rend(self)

    def clear(self):
        return _map.StrStrMap_clear(self)

    def get_allocator(self):
        return _map.StrStrMap_get_allocator(self)

    def count(self, x):
        return _map.StrStrMap_count(self, x)

    def erase(self, *args):
        return _map.StrStrMap_erase(self, *args)

    def find(self, x):
        return _map.StrStrMap_find(self, x)

    def lower_bound(self, x):
        return _map.StrStrMap_lower_bound(self, x)

    def upper_bound(self, x):
        return _map.StrStrMap_upper_bound(self, x)
    __swig_destroy__ = _map.delete_StrStrMap

# Register StrStrMap in _map:
_map.StrStrMap_swigregister(StrStrMap)

