# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _multimap
else:
    import _multimap

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _multimap.delete_SwigPyIterator

    def value(self):
        return _multimap.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _multimap.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _multimap.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _multimap.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _multimap.SwigPyIterator_equal(self, x)

    def copy(self):
        return _multimap.SwigPyIterator_copy(self)

    def next(self):
        return _multimap.SwigPyIterator_next(self)

    def __next__(self):
        return _multimap.SwigPyIterator___next__(self)

    def previous(self):
        return _multimap.SwigPyIterator_previous(self)

    def advance(self, n):
        return _multimap.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _multimap.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _multimap.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _multimap.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _multimap.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _multimap.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _multimap.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _multimap:
_multimap.SwigPyIterator_swigregister(SwigPyIterator)
class IntIntMultimap(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _multimap.IntIntMultimap_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _multimap.IntIntMultimap___nonzero__(self)

    def __bool__(self):
        return _multimap.IntIntMultimap___bool__(self)

    def __len__(self):
        return _multimap.IntIntMultimap___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _multimap.IntIntMultimap___getitem__(self, key)

    def __delitem__(self, key):
        return _multimap.IntIntMultimap___delitem__(self, key)

    def has_key(self, key):
        return _multimap.IntIntMultimap_has_key(self, key)

    def keys(self):
        return _multimap.IntIntMultimap_keys(self)

    def values(self):
        return _multimap.IntIntMultimap_values(self)

    def items(self):
        return _multimap.IntIntMultimap_items(self)

    def __contains__(self, key):
        return _multimap.IntIntMultimap___contains__(self, key)

    def key_iterator(self):
        return _multimap.IntIntMultimap_key_iterator(self)

    def value_iterator(self):
        return _multimap.IntIntMultimap_value_iterator(self)

    def __setitem__(self, *args):
        return _multimap.IntIntMultimap___setitem__(self, *args)

    def __init__(self, *args):
        _multimap.IntIntMultimap_swiginit(self, _multimap.new_IntIntMultimap(*args))

    def empty(self):
        return _multimap.IntIntMultimap_empty(self)

    def size(self):
        return _multimap.IntIntMultimap_size(self)

    def swap(self, v):
        return _multimap.IntIntMultimap_swap(self, v)

    def begin(self):
        return _multimap.IntIntMultimap_begin(self)

    def end(self):
        return _multimap.IntIntMultimap_end(self)

    def rbegin(self):
        return _multimap.IntIntMultimap_rbegin(self)

    def rend(self):
        return _multimap.IntIntMultimap_rend(self)

    def clear(self):
        return _multimap.IntIntMultimap_clear(self)

    def get_allocator(self):
        return _multimap.IntIntMultimap_get_allocator(self)

    def count(self, x):
        return _multimap.IntIntMultimap_count(self, x)

    def erase(self, *args):
        return _multimap.IntIntMultimap_erase(self, *args)

    def find(self, x):
        return _multimap.IntIntMultimap_find(self, x)

    def lower_bound(self, x):
        return _multimap.IntIntMultimap_lower_bound(self, x)

    def upper_bound(self, x):
        return _multimap.IntIntMultimap_upper_bound(self, x)

    def equal_range(self, *args):
        return _multimap.IntIntMultimap_equal_range(self, *args)
    __swig_destroy__ = _multimap.delete_IntIntMultimap

# Register IntIntMultimap in _multimap:
_multimap.IntIntMultimap_swigregister(IntIntMultimap)
class IntDoubleMultimap(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _multimap.IntDoubleMultimap_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _multimap.IntDoubleMultimap___nonzero__(self)

    def __bool__(self):
        return _multimap.IntDoubleMultimap___bool__(self)

    def __len__(self):
        return _multimap.IntDoubleMultimap___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _multimap.IntDoubleMultimap___getitem__(self, key)

    def __delitem__(self, key):
        return _multimap.IntDoubleMultimap___delitem__(self, key)

    def has_key(self, key):
        return _multimap.IntDoubleMultimap_has_key(self, key)

    def keys(self):
        return _multimap.IntDoubleMultimap_keys(self)

    def values(self):
        return _multimap.IntDoubleMultimap_values(self)

    def items(self):
        return _multimap.IntDoubleMultimap_items(self)

    def __contains__(self, key):
        return _multimap.IntDoubleMultimap___contains__(self, key)

    def key_iterator(self):
        return _multimap.IntDoubleMultimap_key_iterator(self)

    def value_iterator(self):
        return _multimap.IntDoubleMultimap_value_iterator(self)

    def __setitem__(self, *args):
        return _multimap.IntDoubleMultimap___setitem__(self, *args)

    def __init__(self, *args):
        _multimap.IntDoubleMultimap_swiginit(self, _multimap.new_IntDoubleMultimap(*args))

    def empty(self):
        return _multimap.IntDoubleMultimap_empty(self)

    def size(self):
        return _multimap.IntDoubleMultimap_size(self)

    def swap(self, v):
        return _multimap.IntDoubleMultimap_swap(self, v)

    def begin(self):
        return _multimap.IntDoubleMultimap_begin(self)

    def end(self):
        return _multimap.IntDoubleMultimap_end(self)

    def rbegin(self):
        return _multimap.IntDoubleMultimap_rbegin(self)

    def rend(self):
        return _multimap.IntDoubleMultimap_rend(self)

    def clear(self):
        return _multimap.IntDoubleMultimap_clear(self)

    def get_allocator(self):
        return _multimap.IntDoubleMultimap_get_allocator(self)

    def count(self, x):
        return _multimap.IntDoubleMultimap_count(self, x)

    def erase(self, *args):
        return _multimap.IntDoubleMultimap_erase(self, *args)

    def find(self, x):
        return _multimap.IntDoubleMultimap_find(self, x)

    def lower_bound(self, x):
        return _multimap.IntDoubleMultimap_lower_bound(self, x)

    def upper_bound(self, x):
        return _multimap.IntDoubleMultimap_upper_bound(self, x)

    def equal_range(self, *args):
        return _multimap.IntDoubleMultimap_equal_range(self, *args)
    __swig_destroy__ = _multimap.delete_IntDoubleMultimap

# Register IntDoubleMultimap in _multimap:
_multimap.IntDoubleMultimap_swigregister(IntDoubleMultimap)
class StrIntMultimap(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _multimap.StrIntMultimap_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _multimap.StrIntMultimap___nonzero__(self)

    def __bool__(self):
        return _multimap.StrIntMultimap___bool__(self)

    def __len__(self):
        return _multimap.StrIntMultimap___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _multimap.StrIntMultimap___getitem__(self, key)

    def __delitem__(self, key):
        return _multimap.StrIntMultimap___delitem__(self, key)

    def has_key(self, key):
        return _multimap.StrIntMultimap_has_key(self, key)

    def keys(self):
        return _multimap.StrIntMultimap_keys(self)

    def values(self):
        return _multimap.StrIntMultimap_values(self)

    def items(self):
        return _multimap.StrIntMultimap_items(self)

    def __contains__(self, key):
        return _multimap.StrIntMultimap___contains__(self, key)

    def key_iterator(self):
        return _multimap.StrIntMultimap_key_iterator(self)

    def value_iterator(self):
        return _multimap.StrIntMultimap_value_iterator(self)

    def __setitem__(self, *args):
        return _multimap.StrIntMultimap___setitem__(self, *args)

    def __init__(self, *args):
        _multimap.StrIntMultimap_swiginit(self, _multimap.new_StrIntMultimap(*args))

    def empty(self):
        return _multimap.StrIntMultimap_empty(self)

    def size(self):
        return _multimap.StrIntMultimap_size(self)

    def swap(self, v):
        return _multimap.StrIntMultimap_swap(self, v)

    def begin(self):
        return _multimap.StrIntMultimap_begin(self)

    def end(self):
        return _multimap.StrIntMultimap_end(self)

    def rbegin(self):
        return _multimap.StrIntMultimap_rbegin(self)

    def rend(self):
        return _multimap.StrIntMultimap_rend(self)

    def clear(self):
        return _multimap.StrIntMultimap_clear(self)

    def get_allocator(self):
        return _multimap.StrIntMultimap_get_allocator(self)

    def count(self, x):
        return _multimap.StrIntMultimap_count(self, x)

    def erase(self, *args):
        return _multimap.StrIntMultimap_erase(self, *args)

    def find(self, x):
        return _multimap.StrIntMultimap_find(self, x)

    def lower_bound(self, x):
        return _multimap.StrIntMultimap_lower_bound(self, x)

    def upper_bound(self, x):
        return _multimap.StrIntMultimap_upper_bound(self, x)

    def equal_range(self, *args):
        return _multimap.StrIntMultimap_equal_range(self, *args)
    __swig_destroy__ = _multimap.delete_StrIntMultimap

# Register StrIntMultimap in _multimap:
_multimap.StrIntMultimap_swigregister(StrIntMultimap)
class StrStrMultimap(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _multimap.StrStrMultimap_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _multimap.StrStrMultimap___nonzero__(self)

    def __bool__(self):
        return _multimap.StrStrMultimap___bool__(self)

    def __len__(self):
        return _multimap.StrStrMultimap___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _multimap.StrStrMultimap___getitem__(self, key)

    def __delitem__(self, key):
        return _multimap.StrStrMultimap___delitem__(self, key)

    def has_key(self, key):
        return _multimap.StrStrMultimap_has_key(self, key)

    def keys(self):
        return _multimap.StrStrMultimap_keys(self)

    def values(self):
        return _multimap.StrStrMultimap_values(self)

    def items(self):
        return _multimap.StrStrMultimap_items(self)

    def __contains__(self, key):
        return _multimap.StrStrMultimap___contains__(self, key)

    def key_iterator(self):
        return _multimap.StrStrMultimap_key_iterator(self)

    def value_iterator(self):
        return _multimap.StrStrMultimap_value_iterator(self)

    def __setitem__(self, *args):
        return _multimap.StrStrMultimap___setitem__(self, *args)

    def __init__(self, *args):
        _multimap.StrStrMultimap_swiginit(self, _multimap.new_StrStrMultimap(*args))

    def empty(self):
        return _multimap.StrStrMultimap_empty(self)

    def size(self):
        return _multimap.StrStrMultimap_size(self)

    def swap(self, v):
        return _multimap.StrStrMultimap_swap(self, v)

    def begin(self):
        return _multimap.StrStrMultimap_begin(self)

    def end(self):
        return _multimap.StrStrMultimap_end(self)

    def rbegin(self):
        return _multimap.StrStrMultimap_rbegin(self)

    def rend(self):
        return _multimap.StrStrMultimap_rend(self)

    def clear(self):
        return _multimap.StrStrMultimap_clear(self)

    def get_allocator(self):
        return _multimap.StrStrMultimap_get_allocator(self)

    def count(self, x):
        return _multimap.StrStrMultimap_count(self, x)

    def erase(self, *args):
        return _multimap.StrStrMultimap_erase(self, *args)

    def find(self, x):
        return _multimap.StrStrMultimap_find(self, x)

    def lower_bound(self, x):
        return _multimap.StrStrMultimap_lower_bound(self, x)

    def upper_bound(self, x):
        return _multimap.StrStrMultimap_upper_bound(self, x)

    def equal_range(self, *args):
        return _multimap.StrStrMultimap_equal_range(self, *args)
    __swig_destroy__ = _multimap.delete_StrStrMultimap

# Register StrStrMultimap in _multimap:
_multimap.StrStrMultimap_swigregister(StrStrMultimap)

