# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _multiset
else:
    import _multiset

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _multiset.delete_SwigPyIterator

    def value(self):
        return _multiset.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _multiset.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _multiset.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _multiset.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _multiset.SwigPyIterator_equal(self, x)

    def copy(self):
        return _multiset.SwigPyIterator_copy(self)

    def next(self):
        return _multiset.SwigPyIterator_next(self)

    def __next__(self):
        return _multiset.SwigPyIterator___next__(self)

    def previous(self):
        return _multiset.SwigPyIterator_previous(self)

    def advance(self, n):
        return _multiset.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _multiset.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _multiset.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _multiset.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _multiset.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _multiset.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _multiset.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _multiset:
_multiset.SwigPyIterator_swigregister(SwigPyIterator)
class IntMultiset(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _multiset.IntMultiset_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _multiset.IntMultiset___nonzero__(self)

    def __bool__(self):
        return _multiset.IntMultiset___bool__(self)

    def __len__(self):
        return _multiset.IntMultiset___len__(self)

    def append(self, x):
        return _multiset.IntMultiset_append(self, x)

    def __contains__(self, x):
        return _multiset.IntMultiset___contains__(self, x)

    def __getitem__(self, i):
        return _multiset.IntMultiset___getitem__(self, i)

    def add(self, x):
        return _multiset.IntMultiset_add(self, x)

    def discard(self, x):
        return _multiset.IntMultiset_discard(self, x)

    def __init__(self, *args):
        _multiset.IntMultiset_swiginit(self, _multiset.new_IntMultiset(*args))

    def empty(self):
        return _multiset.IntMultiset_empty(self)

    def size(self):
        return _multiset.IntMultiset_size(self)

    def clear(self):
        return _multiset.IntMultiset_clear(self)

    def swap(self, v):
        return _multiset.IntMultiset_swap(self, v)

    def count(self, x):
        return _multiset.IntMultiset_count(self, x)

    def begin(self):
        return _multiset.IntMultiset_begin(self)

    def end(self):
        return _multiset.IntMultiset_end(self)

    def rbegin(self):
        return _multiset.IntMultiset_rbegin(self)

    def rend(self):
        return _multiset.IntMultiset_rend(self)

    def erase(self, *args):
        return _multiset.IntMultiset_erase(self, *args)

    def find(self, x):
        return _multiset.IntMultiset_find(self, x)

    def lower_bound(self, x):
        return _multiset.IntMultiset_lower_bound(self, x)

    def upper_bound(self, x):
        return _multiset.IntMultiset_upper_bound(self, x)

    def equal_range(self, x):
        return _multiset.IntMultiset_equal_range(self, x)
    __swig_destroy__ = _multiset.delete_IntMultiset

# Register IntMultiset in _multiset:
_multiset.IntMultiset_swigregister(IntMultiset)
class DoubleMultiset(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _multiset.DoubleMultiset_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _multiset.DoubleMultiset___nonzero__(self)

    def __bool__(self):
        return _multiset.DoubleMultiset___bool__(self)

    def __len__(self):
        return _multiset.DoubleMultiset___len__(self)

    def append(self, x):
        return _multiset.DoubleMultiset_append(self, x)

    def __contains__(self, x):
        return _multiset.DoubleMultiset___contains__(self, x)

    def __getitem__(self, i):
        return _multiset.DoubleMultiset___getitem__(self, i)

    def add(self, x):
        return _multiset.DoubleMultiset_add(self, x)

    def discard(self, x):
        return _multiset.DoubleMultiset_discard(self, x)

    def __init__(self, *args):
        _multiset.DoubleMultiset_swiginit(self, _multiset.new_DoubleMultiset(*args))

    def empty(self):
        return _multiset.DoubleMultiset_empty(self)

    def size(self):
        return _multiset.DoubleMultiset_size(self)

    def clear(self):
        return _multiset.DoubleMultiset_clear(self)

    def swap(self, v):
        return _multiset.DoubleMultiset_swap(self, v)

    def count(self, x):
        return _multiset.DoubleMultiset_count(self, x)

    def begin(self):
        return _multiset.DoubleMultiset_begin(self)

    def end(self):
        return _multiset.DoubleMultiset_end(self)

    def rbegin(self):
        return _multiset.DoubleMultiset_rbegin(self)

    def rend(self):
        return _multiset.DoubleMultiset_rend(self)

    def erase(self, *args):
        return _multiset.DoubleMultiset_erase(self, *args)

    def find(self, x):
        return _multiset.DoubleMultiset_find(self, x)

    def lower_bound(self, x):
        return _multiset.DoubleMultiset_lower_bound(self, x)

    def upper_bound(self, x):
        return _multiset.DoubleMultiset_upper_bound(self, x)

    def equal_range(self, x):
        return _multiset.DoubleMultiset_equal_range(self, x)
    __swig_destroy__ = _multiset.delete_DoubleMultiset

# Register DoubleMultiset in _multiset:
_multiset.DoubleMultiset_swigregister(DoubleMultiset)
class StrMultiset(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _multiset.StrMultiset_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _multiset.StrMultiset___nonzero__(self)

    def __bool__(self):
        return _multiset.StrMultiset___bool__(self)

    def __len__(self):
        return _multiset.StrMultiset___len__(self)

    def append(self, x):
        return _multiset.StrMultiset_append(self, x)

    def __contains__(self, x):
        return _multiset.StrMultiset___contains__(self, x)

    def __getitem__(self, i):
        return _multiset.StrMultiset___getitem__(self, i)

    def add(self, x):
        return _multiset.StrMultiset_add(self, x)

    def discard(self, x):
        return _multiset.StrMultiset_discard(self, x)

    def __init__(self, *args):
        _multiset.StrMultiset_swiginit(self, _multiset.new_StrMultiset(*args))

    def empty(self):
        return _multiset.StrMultiset_empty(self)

    def size(self):
        return _multiset.StrMultiset_size(self)

    def clear(self):
        return _multiset.StrMultiset_clear(self)

    def swap(self, v):
        return _multiset.StrMultiset_swap(self, v)

    def count(self, x):
        return _multiset.StrMultiset_count(self, x)

    def begin(self):
        return _multiset.StrMultiset_begin(self)

    def end(self):
        return _multiset.StrMultiset_end(self)

    def rbegin(self):
        return _multiset.StrMultiset_rbegin(self)

    def rend(self):
        return _multiset.StrMultiset_rend(self)

    def erase(self, *args):
        return _multiset.StrMultiset_erase(self, *args)

    def find(self, x):
        return _multiset.StrMultiset_find(self, x)

    def lower_bound(self, x):
        return _multiset.StrMultiset_lower_bound(self, x)

    def upper_bound(self, x):
        return _multiset.StrMultiset_upper_bound(self, x)

    def equal_range(self, x):
        return _multiset.StrMultiset_equal_range(self, x)
    __swig_destroy__ = _multiset.delete_StrMultiset

# Register StrMultiset in _multiset:
_multiset.StrMultiset_swigregister(StrMultiset)

