# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _set
else:
    import _set

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _set.delete_SwigPyIterator

    def value(self):
        return _set.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _set.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _set.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _set.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _set.SwigPyIterator_equal(self, x)

    def copy(self):
        return _set.SwigPyIterator_copy(self)

    def next(self):
        return _set.SwigPyIterator_next(self)

    def __next__(self):
        return _set.SwigPyIterator___next__(self)

    def previous(self):
        return _set.SwigPyIterator_previous(self)

    def advance(self, n):
        return _set.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _set.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _set.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _set.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _set.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _set.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _set.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _set:
_set.SwigPyIterator_swigregister(SwigPyIterator)
class IntSet(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _set.IntSet_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _set.IntSet___nonzero__(self)

    def __bool__(self):
        return _set.IntSet___bool__(self)

    def __len__(self):
        return _set.IntSet___len__(self)

    def append(self, x):
        return _set.IntSet_append(self, x)

    def __contains__(self, x):
        return _set.IntSet___contains__(self, x)

    def __getitem__(self, i):
        return _set.IntSet___getitem__(self, i)

    def add(self, x):
        return _set.IntSet_add(self, x)

    def discard(self, x):
        return _set.IntSet_discard(self, x)

    def __init__(self, *args):
        _set.IntSet_swiginit(self, _set.new_IntSet(*args))

    def empty(self):
        return _set.IntSet_empty(self)

    def size(self):
        return _set.IntSet_size(self)

    def clear(self):
        return _set.IntSet_clear(self)

    def swap(self, v):
        return _set.IntSet_swap(self, v)

    def count(self, x):
        return _set.IntSet_count(self, x)

    def begin(self):
        return _set.IntSet_begin(self)

    def end(self):
        return _set.IntSet_end(self)

    def rbegin(self):
        return _set.IntSet_rbegin(self)

    def rend(self):
        return _set.IntSet_rend(self)

    def erase(self, *args):
        return _set.IntSet_erase(self, *args)

    def find(self, x):
        return _set.IntSet_find(self, x)

    def lower_bound(self, x):
        return _set.IntSet_lower_bound(self, x)

    def upper_bound(self, x):
        return _set.IntSet_upper_bound(self, x)

    def equal_range(self, x):
        return _set.IntSet_equal_range(self, x)

    def insert(self, __x):
        return _set.IntSet_insert(self, __x)
    __swig_destroy__ = _set.delete_IntSet

# Register IntSet in _set:
_set.IntSet_swigregister(IntSet)
class DoubleSet(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _set.DoubleSet_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _set.DoubleSet___nonzero__(self)

    def __bool__(self):
        return _set.DoubleSet___bool__(self)

    def __len__(self):
        return _set.DoubleSet___len__(self)

    def append(self, x):
        return _set.DoubleSet_append(self, x)

    def __contains__(self, x):
        return _set.DoubleSet___contains__(self, x)

    def __getitem__(self, i):
        return _set.DoubleSet___getitem__(self, i)

    def add(self, x):
        return _set.DoubleSet_add(self, x)

    def discard(self, x):
        return _set.DoubleSet_discard(self, x)

    def __init__(self, *args):
        _set.DoubleSet_swiginit(self, _set.new_DoubleSet(*args))

    def empty(self):
        return _set.DoubleSet_empty(self)

    def size(self):
        return _set.DoubleSet_size(self)

    def clear(self):
        return _set.DoubleSet_clear(self)

    def swap(self, v):
        return _set.DoubleSet_swap(self, v)

    def count(self, x):
        return _set.DoubleSet_count(self, x)

    def begin(self):
        return _set.DoubleSet_begin(self)

    def end(self):
        return _set.DoubleSet_end(self)

    def rbegin(self):
        return _set.DoubleSet_rbegin(self)

    def rend(self):
        return _set.DoubleSet_rend(self)

    def erase(self, *args):
        return _set.DoubleSet_erase(self, *args)

    def find(self, x):
        return _set.DoubleSet_find(self, x)

    def lower_bound(self, x):
        return _set.DoubleSet_lower_bound(self, x)

    def upper_bound(self, x):
        return _set.DoubleSet_upper_bound(self, x)

    def equal_range(self, x):
        return _set.DoubleSet_equal_range(self, x)

    def insert(self, __x):
        return _set.DoubleSet_insert(self, __x)
    __swig_destroy__ = _set.delete_DoubleSet

# Register DoubleSet in _set:
_set.DoubleSet_swigregister(DoubleSet)
class StrSet(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _set.StrSet_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _set.StrSet___nonzero__(self)

    def __bool__(self):
        return _set.StrSet___bool__(self)

    def __len__(self):
        return _set.StrSet___len__(self)

    def append(self, x):
        return _set.StrSet_append(self, x)

    def __contains__(self, x):
        return _set.StrSet___contains__(self, x)

    def __getitem__(self, i):
        return _set.StrSet___getitem__(self, i)

    def add(self, x):
        return _set.StrSet_add(self, x)

    def discard(self, x):
        return _set.StrSet_discard(self, x)

    def __init__(self, *args):
        _set.StrSet_swiginit(self, _set.new_StrSet(*args))

    def empty(self):
        return _set.StrSet_empty(self)

    def size(self):
        return _set.StrSet_size(self)

    def clear(self):
        return _set.StrSet_clear(self)

    def swap(self, v):
        return _set.StrSet_swap(self, v)

    def count(self, x):
        return _set.StrSet_count(self, x)

    def begin(self):
        return _set.StrSet_begin(self)

    def end(self):
        return _set.StrSet_end(self)

    def rbegin(self):
        return _set.StrSet_rbegin(self)

    def rend(self):
        return _set.StrSet_rend(self)

    def erase(self, *args):
        return _set.StrSet_erase(self, *args)

    def find(self, x):
        return _set.StrSet_find(self, x)

    def lower_bound(self, x):
        return _set.StrSet_lower_bound(self, x)

    def upper_bound(self, x):
        return _set.StrSet_upper_bound(self, x)

    def equal_range(self, x):
        return _set.StrSet_equal_range(self, x)

    def insert(self, __x):
        return _set.StrSet_insert(self, __x)
    __swig_destroy__ = _set.delete_StrSet

# Register StrSet in _set:
_set.StrSet_swigregister(StrSet)

