# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _unordered_multiset
else:
    import _unordered_multiset

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _unordered_multiset.delete_SwigPyIterator

    def value(self):
        return _unordered_multiset.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _unordered_multiset.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _unordered_multiset.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _unordered_multiset.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _unordered_multiset.SwigPyIterator_equal(self, x)

    def copy(self):
        return _unordered_multiset.SwigPyIterator_copy(self)

    def next(self):
        return _unordered_multiset.SwigPyIterator_next(self)

    def __next__(self):
        return _unordered_multiset.SwigPyIterator___next__(self)

    def previous(self):
        return _unordered_multiset.SwigPyIterator_previous(self)

    def advance(self, n):
        return _unordered_multiset.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _unordered_multiset.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _unordered_multiset.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _unordered_multiset.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _unordered_multiset.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _unordered_multiset.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _unordered_multiset.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _unordered_multiset:
_unordered_multiset.SwigPyIterator_swigregister(SwigPyIterator)
class IntUnorderedMultiset(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _unordered_multiset.IntUnorderedMultiset_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _unordered_multiset.IntUnorderedMultiset___nonzero__(self)

    def __bool__(self):
        return _unordered_multiset.IntUnorderedMultiset___bool__(self)

    def __len__(self):
        return _unordered_multiset.IntUnorderedMultiset___len__(self)

    def append(self, x):
        return _unordered_multiset.IntUnorderedMultiset_append(self, x)

    def __contains__(self, x):
        return _unordered_multiset.IntUnorderedMultiset___contains__(self, x)

    def __getitem__(self, i):
        return _unordered_multiset.IntUnorderedMultiset___getitem__(self, i)

    def __init__(self, *args):
        _unordered_multiset.IntUnorderedMultiset_swiginit(self, _unordered_multiset.new_IntUnorderedMultiset(*args))

    def empty(self):
        return _unordered_multiset.IntUnorderedMultiset_empty(self)

    def size(self):
        return _unordered_multiset.IntUnorderedMultiset_size(self)

    def clear(self):
        return _unordered_multiset.IntUnorderedMultiset_clear(self)

    def swap(self, v):
        return _unordered_multiset.IntUnorderedMultiset_swap(self, v)

    def count(self, x):
        return _unordered_multiset.IntUnorderedMultiset_count(self, x)

    def begin(self):
        return _unordered_multiset.IntUnorderedMultiset_begin(self)

    def end(self):
        return _unordered_multiset.IntUnorderedMultiset_end(self)

    def erase(self, *args):
        return _unordered_multiset.IntUnorderedMultiset_erase(self, *args)

    def find(self, x):
        return _unordered_multiset.IntUnorderedMultiset_find(self, x)

    def equal_range(self, x):
        return _unordered_multiset.IntUnorderedMultiset_equal_range(self, x)
    __swig_destroy__ = _unordered_multiset.delete_IntUnorderedMultiset

# Register IntUnorderedMultiset in _unordered_multiset:
_unordered_multiset.IntUnorderedMultiset_swigregister(IntUnorderedMultiset)
class DoubleUnorderedMultiset(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _unordered_multiset.DoubleUnorderedMultiset_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _unordered_multiset.DoubleUnorderedMultiset___nonzero__(self)

    def __bool__(self):
        return _unordered_multiset.DoubleUnorderedMultiset___bool__(self)

    def __len__(self):
        return _unordered_multiset.DoubleUnorderedMultiset___len__(self)

    def append(self, x):
        return _unordered_multiset.DoubleUnorderedMultiset_append(self, x)

    def __contains__(self, x):
        return _unordered_multiset.DoubleUnorderedMultiset___contains__(self, x)

    def __getitem__(self, i):
        return _unordered_multiset.DoubleUnorderedMultiset___getitem__(self, i)

    def __init__(self, *args):
        _unordered_multiset.DoubleUnorderedMultiset_swiginit(self, _unordered_multiset.new_DoubleUnorderedMultiset(*args))

    def empty(self):
        return _unordered_multiset.DoubleUnorderedMultiset_empty(self)

    def size(self):
        return _unordered_multiset.DoubleUnorderedMultiset_size(self)

    def clear(self):
        return _unordered_multiset.DoubleUnorderedMultiset_clear(self)

    def swap(self, v):
        return _unordered_multiset.DoubleUnorderedMultiset_swap(self, v)

    def count(self, x):
        return _unordered_multiset.DoubleUnorderedMultiset_count(self, x)

    def begin(self):
        return _unordered_multiset.DoubleUnorderedMultiset_begin(self)

    def end(self):
        return _unordered_multiset.DoubleUnorderedMultiset_end(self)

    def erase(self, *args):
        return _unordered_multiset.DoubleUnorderedMultiset_erase(self, *args)

    def find(self, x):
        return _unordered_multiset.DoubleUnorderedMultiset_find(self, x)

    def equal_range(self, x):
        return _unordered_multiset.DoubleUnorderedMultiset_equal_range(self, x)
    __swig_destroy__ = _unordered_multiset.delete_DoubleUnorderedMultiset

# Register DoubleUnorderedMultiset in _unordered_multiset:
_unordered_multiset.DoubleUnorderedMultiset_swigregister(DoubleUnorderedMultiset)
class StrUnorderedMultiset(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _unordered_multiset.StrUnorderedMultiset_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _unordered_multiset.StrUnorderedMultiset___nonzero__(self)

    def __bool__(self):
        return _unordered_multiset.StrUnorderedMultiset___bool__(self)

    def __len__(self):
        return _unordered_multiset.StrUnorderedMultiset___len__(self)

    def append(self, x):
        return _unordered_multiset.StrUnorderedMultiset_append(self, x)

    def __contains__(self, x):
        return _unordered_multiset.StrUnorderedMultiset___contains__(self, x)

    def __getitem__(self, i):
        return _unordered_multiset.StrUnorderedMultiset___getitem__(self, i)

    def __init__(self, *args):
        _unordered_multiset.StrUnorderedMultiset_swiginit(self, _unordered_multiset.new_StrUnorderedMultiset(*args))

    def empty(self):
        return _unordered_multiset.StrUnorderedMultiset_empty(self)

    def size(self):
        return _unordered_multiset.StrUnorderedMultiset_size(self)

    def clear(self):
        return _unordered_multiset.StrUnorderedMultiset_clear(self)

    def swap(self, v):
        return _unordered_multiset.StrUnorderedMultiset_swap(self, v)

    def count(self, x):
        return _unordered_multiset.StrUnorderedMultiset_count(self, x)

    def begin(self):
        return _unordered_multiset.StrUnorderedMultiset_begin(self)

    def end(self):
        return _unordered_multiset.StrUnorderedMultiset_end(self)

    def erase(self, *args):
        return _unordered_multiset.StrUnorderedMultiset_erase(self, *args)

    def find(self, x):
        return _unordered_multiset.StrUnorderedMultiset_find(self, x)

    def equal_range(self, x):
        return _unordered_multiset.StrUnorderedMultiset_equal_range(self, x)
    __swig_destroy__ = _unordered_multiset.delete_StrUnorderedMultiset

# Register StrUnorderedMultiset in _unordered_multiset:
_unordered_multiset.StrUnorderedMultiset_swigregister(StrUnorderedMultiset)

