# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _unordered_map
else:
    import _unordered_map

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _unordered_map.delete_SwigPyIterator

    def value(self):
        return _unordered_map.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _unordered_map.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _unordered_map.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _unordered_map.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _unordered_map.SwigPyIterator_equal(self, x)

    def copy(self):
        return _unordered_map.SwigPyIterator_copy(self)

    def next(self):
        return _unordered_map.SwigPyIterator_next(self)

    def __next__(self):
        return _unordered_map.SwigPyIterator___next__(self)

    def previous(self):
        return _unordered_map.SwigPyIterator_previous(self)

    def advance(self, n):
        return _unordered_map.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _unordered_map.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _unordered_map.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _unordered_map.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _unordered_map.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _unordered_map.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _unordered_map.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _unordered_map:
_unordered_map.SwigPyIterator_swigregister(SwigPyIterator)
class IntIntUnorderedMap(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _unordered_map.IntIntUnorderedMap_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _unordered_map.IntIntUnorderedMap___nonzero__(self)

    def __bool__(self):
        return _unordered_map.IntIntUnorderedMap___bool__(self)

    def __len__(self):
        return _unordered_map.IntIntUnorderedMap___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _unordered_map.IntIntUnorderedMap___getitem__(self, key)

    def __delitem__(self, key):
        return _unordered_map.IntIntUnorderedMap___delitem__(self, key)

    def has_key(self, key):
        return _unordered_map.IntIntUnorderedMap_has_key(self, key)

    def keys(self):
        return _unordered_map.IntIntUnorderedMap_keys(self)

    def values(self):
        return _unordered_map.IntIntUnorderedMap_values(self)

    def items(self):
        return _unordered_map.IntIntUnorderedMap_items(self)

    def __contains__(self, key):
        return _unordered_map.IntIntUnorderedMap___contains__(self, key)

    def key_iterator(self):
        return _unordered_map.IntIntUnorderedMap_key_iterator(self)

    def value_iterator(self):
        return _unordered_map.IntIntUnorderedMap_value_iterator(self)

    def __setitem__(self, *args):
        return _unordered_map.IntIntUnorderedMap___setitem__(self, *args)

    def asdict(self):
        return _unordered_map.IntIntUnorderedMap_asdict(self)

    def __init__(self, *args):
        _unordered_map.IntIntUnorderedMap_swiginit(self, _unordered_map.new_IntIntUnorderedMap(*args))

    def empty(self):
        return _unordered_map.IntIntUnorderedMap_empty(self)

    def size(self):
        return _unordered_map.IntIntUnorderedMap_size(self)

    def swap(self, v):
        return _unordered_map.IntIntUnorderedMap_swap(self, v)

    def begin(self):
        return _unordered_map.IntIntUnorderedMap_begin(self)

    def end(self):
        return _unordered_map.IntIntUnorderedMap_end(self)

    def clear(self):
        return _unordered_map.IntIntUnorderedMap_clear(self)

    def get_allocator(self):
        return _unordered_map.IntIntUnorderedMap_get_allocator(self)

    def count(self, x):
        return _unordered_map.IntIntUnorderedMap_count(self, x)

    def erase(self, *args):
        return _unordered_map.IntIntUnorderedMap_erase(self, *args)

    def find(self, x):
        return _unordered_map.IntIntUnorderedMap_find(self, x)
    __swig_destroy__ = _unordered_map.delete_IntIntUnorderedMap

# Register IntIntUnorderedMap in _unordered_map:
_unordered_map.IntIntUnorderedMap_swigregister(IntIntUnorderedMap)
class IntDoubleUnorderedMap(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _unordered_map.IntDoubleUnorderedMap_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _unordered_map.IntDoubleUnorderedMap___nonzero__(self)

    def __bool__(self):
        return _unordered_map.IntDoubleUnorderedMap___bool__(self)

    def __len__(self):
        return _unordered_map.IntDoubleUnorderedMap___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _unordered_map.IntDoubleUnorderedMap___getitem__(self, key)

    def __delitem__(self, key):
        return _unordered_map.IntDoubleUnorderedMap___delitem__(self, key)

    def has_key(self, key):
        return _unordered_map.IntDoubleUnorderedMap_has_key(self, key)

    def keys(self):
        return _unordered_map.IntDoubleUnorderedMap_keys(self)

    def values(self):
        return _unordered_map.IntDoubleUnorderedMap_values(self)

    def items(self):
        return _unordered_map.IntDoubleUnorderedMap_items(self)

    def __contains__(self, key):
        return _unordered_map.IntDoubleUnorderedMap___contains__(self, key)

    def key_iterator(self):
        return _unordered_map.IntDoubleUnorderedMap_key_iterator(self)

    def value_iterator(self):
        return _unordered_map.IntDoubleUnorderedMap_value_iterator(self)

    def __setitem__(self, *args):
        return _unordered_map.IntDoubleUnorderedMap___setitem__(self, *args)

    def asdict(self):
        return _unordered_map.IntDoubleUnorderedMap_asdict(self)

    def __init__(self, *args):
        _unordered_map.IntDoubleUnorderedMap_swiginit(self, _unordered_map.new_IntDoubleUnorderedMap(*args))

    def empty(self):
        return _unordered_map.IntDoubleUnorderedMap_empty(self)

    def size(self):
        return _unordered_map.IntDoubleUnorderedMap_size(self)

    def swap(self, v):
        return _unordered_map.IntDoubleUnorderedMap_swap(self, v)

    def begin(self):
        return _unordered_map.IntDoubleUnorderedMap_begin(self)

    def end(self):
        return _unordered_map.IntDoubleUnorderedMap_end(self)

    def clear(self):
        return _unordered_map.IntDoubleUnorderedMap_clear(self)

    def get_allocator(self):
        return _unordered_map.IntDoubleUnorderedMap_get_allocator(self)

    def count(self, x):
        return _unordered_map.IntDoubleUnorderedMap_count(self, x)

    def erase(self, *args):
        return _unordered_map.IntDoubleUnorderedMap_erase(self, *args)

    def find(self, x):
        return _unordered_map.IntDoubleUnorderedMap_find(self, x)
    __swig_destroy__ = _unordered_map.delete_IntDoubleUnorderedMap

# Register IntDoubleUnorderedMap in _unordered_map:
_unordered_map.IntDoubleUnorderedMap_swigregister(IntDoubleUnorderedMap)
class StrIntUnorderedMap(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _unordered_map.StrIntUnorderedMap_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _unordered_map.StrIntUnorderedMap___nonzero__(self)

    def __bool__(self):
        return _unordered_map.StrIntUnorderedMap___bool__(self)

    def __len__(self):
        return _unordered_map.StrIntUnorderedMap___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _unordered_map.StrIntUnorderedMap___getitem__(self, key)

    def __delitem__(self, key):
        return _unordered_map.StrIntUnorderedMap___delitem__(self, key)

    def has_key(self, key):
        return _unordered_map.StrIntUnorderedMap_has_key(self, key)

    def keys(self):
        return _unordered_map.StrIntUnorderedMap_keys(self)

    def values(self):
        return _unordered_map.StrIntUnorderedMap_values(self)

    def items(self):
        return _unordered_map.StrIntUnorderedMap_items(self)

    def __contains__(self, key):
        return _unordered_map.StrIntUnorderedMap___contains__(self, key)

    def key_iterator(self):
        return _unordered_map.StrIntUnorderedMap_key_iterator(self)

    def value_iterator(self):
        return _unordered_map.StrIntUnorderedMap_value_iterator(self)

    def __setitem__(self, *args):
        return _unordered_map.StrIntUnorderedMap___setitem__(self, *args)

    def asdict(self):
        return _unordered_map.StrIntUnorderedMap_asdict(self)

    def __init__(self, *args):
        _unordered_map.StrIntUnorderedMap_swiginit(self, _unordered_map.new_StrIntUnorderedMap(*args))

    def empty(self):
        return _unordered_map.StrIntUnorderedMap_empty(self)

    def size(self):
        return _unordered_map.StrIntUnorderedMap_size(self)

    def swap(self, v):
        return _unordered_map.StrIntUnorderedMap_swap(self, v)

    def begin(self):
        return _unordered_map.StrIntUnorderedMap_begin(self)

    def end(self):
        return _unordered_map.StrIntUnorderedMap_end(self)

    def clear(self):
        return _unordered_map.StrIntUnorderedMap_clear(self)

    def get_allocator(self):
        return _unordered_map.StrIntUnorderedMap_get_allocator(self)

    def count(self, x):
        return _unordered_map.StrIntUnorderedMap_count(self, x)

    def erase(self, *args):
        return _unordered_map.StrIntUnorderedMap_erase(self, *args)

    def find(self, x):
        return _unordered_map.StrIntUnorderedMap_find(self, x)
    __swig_destroy__ = _unordered_map.delete_StrIntUnorderedMap

# Register StrIntUnorderedMap in _unordered_map:
_unordered_map.StrIntUnorderedMap_swigregister(StrIntUnorderedMap)
class StrStrUnorderedMap(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _unordered_map.StrStrUnorderedMap_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _unordered_map.StrStrUnorderedMap___nonzero__(self)

    def __bool__(self):
        return _unordered_map.StrStrUnorderedMap___bool__(self)

    def __len__(self):
        return _unordered_map.StrStrUnorderedMap___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _unordered_map.StrStrUnorderedMap___getitem__(self, key)

    def __delitem__(self, key):
        return _unordered_map.StrStrUnorderedMap___delitem__(self, key)

    def has_key(self, key):
        return _unordered_map.StrStrUnorderedMap_has_key(self, key)

    def keys(self):
        return _unordered_map.StrStrUnorderedMap_keys(self)

    def values(self):
        return _unordered_map.StrStrUnorderedMap_values(self)

    def items(self):
        return _unordered_map.StrStrUnorderedMap_items(self)

    def __contains__(self, key):
        return _unordered_map.StrStrUnorderedMap___contains__(self, key)

    def key_iterator(self):
        return _unordered_map.StrStrUnorderedMap_key_iterator(self)

    def value_iterator(self):
        return _unordered_map.StrStrUnorderedMap_value_iterator(self)

    def __setitem__(self, *args):
        return _unordered_map.StrStrUnorderedMap___setitem__(self, *args)

    def asdict(self):
        return _unordered_map.StrStrUnorderedMap_asdict(self)

    def __init__(self, *args):
        _unordered_map.StrStrUnorderedMap_swiginit(self, _unordered_map.new_StrStrUnorderedMap(*args))

    def empty(self):
        return _unordered_map.StrStrUnorderedMap_empty(self)

    def size(self):
        return _unordered_map.StrStrUnorderedMap_size(self)

    def swap(self, v):
        return _unordered_map.StrStrUnorderedMap_swap(self, v)

    def begin(self):
        return _unordered_map.StrStrUnorderedMap_begin(self)

    def end(self):
        return _unordered_map.StrStrUnorderedMap_end(self)

    def clear(self):
        return _unordered_map.StrStrUnorderedMap_clear(self)

    def get_allocator(self):
        return _unordered_map.StrStrUnorderedMap_get_allocator(self)

    def count(self, x):
        return _unordered_map.StrStrUnorderedMap_count(self, x)

    def erase(self, *args):
        return _unordered_map.StrStrUnorderedMap_erase(self, *args)

    def find(self, x):
        return _unordered_map.StrStrUnorderedMap_find(self, x)
    __swig_destroy__ = _unordered_map.delete_StrStrUnorderedMap

# Register StrStrUnorderedMap in _unordered_map:
_unordered_map.StrStrUnorderedMap_swigregister(StrStrUnorderedMap)

