# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _vector
else:
    import _vector

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _vector.delete_SwigPyIterator

    def value(self):
        return _vector.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _vector.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _vector.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _vector.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _vector.SwigPyIterator_equal(self, x)

    def copy(self):
        return _vector.SwigPyIterator_copy(self)

    def next(self):
        return _vector.SwigPyIterator_next(self)

    def __next__(self):
        return _vector.SwigPyIterator___next__(self)

    def previous(self):
        return _vector.SwigPyIterator_previous(self)

    def advance(self, n):
        return _vector.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _vector.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _vector.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _vector.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _vector.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _vector.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _vector.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _vector:
_vector.SwigPyIterator_swigregister(SwigPyIterator)
class IntVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _vector.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _vector.IntVector___nonzero__(self)

    def __bool__(self):
        return _vector.IntVector___bool__(self)

    def __len__(self):
        return _vector.IntVector___len__(self)

    def __getslice__(self, i, j):
        return _vector.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _vector.IntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _vector.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _vector.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _vector.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _vector.IntVector___setitem__(self, *args)

    def pop(self):
        return _vector.IntVector_pop(self)

    def append(self, x):
        return _vector.IntVector_append(self, x)

    def empty(self):
        return _vector.IntVector_empty(self)

    def size(self):
        return _vector.IntVector_size(self)

    def swap(self, v):
        return _vector.IntVector_swap(self, v)

    def begin(self):
        return _vector.IntVector_begin(self)

    def end(self):
        return _vector.IntVector_end(self)

    def rbegin(self):
        return _vector.IntVector_rbegin(self)

    def rend(self):
        return _vector.IntVector_rend(self)

    def clear(self):
        return _vector.IntVector_clear(self)

    def get_allocator(self):
        return _vector.IntVector_get_allocator(self)

    def pop_back(self):
        return _vector.IntVector_pop_back(self)

    def erase(self, *args):
        return _vector.IntVector_erase(self, *args)

    def __init__(self, *args):
        _vector.IntVector_swiginit(self, _vector.new_IntVector(*args))

    def push_back(self, x):
        return _vector.IntVector_push_back(self, x)

    def front(self):
        return _vector.IntVector_front(self)

    def back(self):
        return _vector.IntVector_back(self)

    def assign(self, n, x):
        return _vector.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _vector.IntVector_resize(self, *args)

    def insert(self, *args):
        return _vector.IntVector_insert(self, *args)

    def reserve(self, n):
        return _vector.IntVector_reserve(self, n)

    def capacity(self):
        return _vector.IntVector_capacity(self)
    __swig_destroy__ = _vector.delete_IntVector

# Register IntVector in _vector:
_vector.IntVector_swigregister(IntVector)
class DoubleVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _vector.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _vector.DoubleVector___nonzero__(self)

    def __bool__(self):
        return _vector.DoubleVector___bool__(self)

    def __len__(self):
        return _vector.DoubleVector___len__(self)

    def __getslice__(self, i, j):
        return _vector.DoubleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _vector.DoubleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _vector.DoubleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _vector.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _vector.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _vector.DoubleVector___setitem__(self, *args)

    def pop(self):
        return _vector.DoubleVector_pop(self)

    def append(self, x):
        return _vector.DoubleVector_append(self, x)

    def empty(self):
        return _vector.DoubleVector_empty(self)

    def size(self):
        return _vector.DoubleVector_size(self)

    def swap(self, v):
        return _vector.DoubleVector_swap(self, v)

    def begin(self):
        return _vector.DoubleVector_begin(self)

    def end(self):
        return _vector.DoubleVector_end(self)

    def rbegin(self):
        return _vector.DoubleVector_rbegin(self)

    def rend(self):
        return _vector.DoubleVector_rend(self)

    def clear(self):
        return _vector.DoubleVector_clear(self)

    def get_allocator(self):
        return _vector.DoubleVector_get_allocator(self)

    def pop_back(self):
        return _vector.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _vector.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        _vector.DoubleVector_swiginit(self, _vector.new_DoubleVector(*args))

    def push_back(self, x):
        return _vector.DoubleVector_push_back(self, x)

    def front(self):
        return _vector.DoubleVector_front(self)

    def back(self):
        return _vector.DoubleVector_back(self)

    def assign(self, n, x):
        return _vector.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _vector.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _vector.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _vector.DoubleVector_reserve(self, n)

    def capacity(self):
        return _vector.DoubleVector_capacity(self)
    __swig_destroy__ = _vector.delete_DoubleVector

# Register DoubleVector in _vector:
_vector.DoubleVector_swigregister(DoubleVector)
class StrVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _vector.StrVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _vector.StrVector___nonzero__(self)

    def __bool__(self):
        return _vector.StrVector___bool__(self)

    def __len__(self):
        return _vector.StrVector___len__(self)

    def __getslice__(self, i, j):
        return _vector.StrVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _vector.StrVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _vector.StrVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _vector.StrVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _vector.StrVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _vector.StrVector___setitem__(self, *args)

    def pop(self):
        return _vector.StrVector_pop(self)

    def append(self, x):
        return _vector.StrVector_append(self, x)

    def empty(self):
        return _vector.StrVector_empty(self)

    def size(self):
        return _vector.StrVector_size(self)

    def swap(self, v):
        return _vector.StrVector_swap(self, v)

    def begin(self):
        return _vector.StrVector_begin(self)

    def end(self):
        return _vector.StrVector_end(self)

    def rbegin(self):
        return _vector.StrVector_rbegin(self)

    def rend(self):
        return _vector.StrVector_rend(self)

    def clear(self):
        return _vector.StrVector_clear(self)

    def get_allocator(self):
        return _vector.StrVector_get_allocator(self)

    def pop_back(self):
        return _vector.StrVector_pop_back(self)

    def erase(self, *args):
        return _vector.StrVector_erase(self, *args)

    def __init__(self, *args):
        _vector.StrVector_swiginit(self, _vector.new_StrVector(*args))

    def push_back(self, x):
        return _vector.StrVector_push_back(self, x)

    def front(self):
        return _vector.StrVector_front(self)

    def back(self):
        return _vector.StrVector_back(self)

    def assign(self, n, x):
        return _vector.StrVector_assign(self, n, x)

    def resize(self, *args):
        return _vector.StrVector_resize(self, *args)

    def insert(self, *args):
        return _vector.StrVector_insert(self, *args)

    def reserve(self, n):
        return _vector.StrVector_reserve(self, n)

    def capacity(self):
        return _vector.StrVector_capacity(self)
    __swig_destroy__ = _vector.delete_StrVector

# Register StrVector in _vector:
_vector.StrVector_swigregister(StrVector)

